/** Declaration file generated by dts-gen */

export const BuildInKeyReflectors: {
    CONSTRUCTOR_NAME: string;
    INTERNAL_TYPE: string;
    METHOD_GET_TYPE: string;
    OBJECT_SHAPE: string;
    PROPERTY_TYPE: string;
};

export const EventKeyPrefix: {
    reflection: string;
    string: string;
};

export const KeyReflectorPriority: {
    HIGH: string;
    LOW: string;
    MEDIUM: string;
};

export function ConstructorKeyReflector(reflectorName: any): any;

export function EventBus(): any;

export function EventBusConfig(): any;

export function EventBusDiagnostics(): any;

export function EventBusError(message: any): void;

export function EventKeyBuilder(config: any, diag: any): any;

export function KeyInfo(reflector: any, key: any): void;

export function KeyReflector(): void;

export function KeyReflectorScanner(config: any): any;

export function MethodKeyReflector(reflectorName: any, methodName: any): any;

export function PropertyKeyReflector(reflectorName: any, propertyName: any): any;

export function Registration(): void;

export function RegistrationContext(eventBus: any, config: any, diagnostics: any): any;

export function RegistrationSetup(registration: any, diagnostic: any): void;

export function ShapeKeyReflector(reflectorName: any): any;

export namespace ConstructorKeyReflector {
    const prototype: {
    };

}

export namespace EventBus {
    const prototype: {
    };

}

export namespace EventBusConfig {
    const prototype: {
    };

}

export namespace EventBusDiagnostics {
    const prototype: {
    };

}

export namespace EventBusError {
    const prototype: {
    };

}

export namespace EventKeyBuilder {
    const prototype: {
    };

}

export namespace KeyInfo {
    const prototype: {
    };

}

export namespace KeyReflector {
    const prototype: {
    };

    function getKey(obj: any): any;

    function getName(): any;

    namespace getKey {
        const prototype: {
        };

    }

    namespace getName {
        const prototype: {
        };

    }

}

export namespace KeyReflectorScanner {
    const prototype: {
    };

}

export namespace MethodKeyReflector {
    const prototype: {
    };

}

export namespace PropertyKeyReflector {
    const prototype: {
    };

}

export namespace Registration {
    const prototype: {
    };

}

export namespace RegistrationContext {
    const prototype: {
    };

}

export namespace RegistrationSetup {
    const prototype: {
    };

}

export namespace ShapeKeyReflector {
    const prototype: {
    };

}

